"""add_tipo_to_usuario

Revision ID: 37858763fa98
Revises: 3d9007205250
Create Date: 2026-06-13 21:55:24.280980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37858763fa98'
down_revision: Union[str, None] = '3d9007205250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('tipo', sa.String(length=100), nullable=False, server_default='TECNICO'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'tipo')
    # ### end Alembic commands ###
