"""create_base_tables_cliente_equipamento_produto

Revision ID: 8673639429cc
Revises: None
Create Date: 2026-06-13 21:14:21.396970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8673639429cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('idcliente', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idcliente'),
    sa.UniqueConstraint('cpf_cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('produtos',
    sa.Column('idproduto', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idproduto')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('equipamentos',
    sa.Column('idequipamento', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('idcliente', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['idcliente'], ['clientes.idcliente'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idequipamento'),
    sa.UniqueConstraint('numero_serie')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipamentos')
    op.drop_table('usuario')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
