"""create_os_and_items_tables_with_index

Revision ID: f5b312378bfa
Revises: 8673639429cc
Create Date: 2026-06-13 21:15:23.553995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b312378bfa'
down_revision: Union[str, None] = '8673639429cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OS',
    sa.Column('idos', sa.Uuid(), nullable=False),
    sa.Column('idcliente', sa.Uuid(), nullable=False),
    sa.Column('idequipamento', sa.Uuid(), nullable=False),
    sa.Column('idtecnico', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('descricao_defeito', sa.String(length=100), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idcliente'], ['clientes.idcliente'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['idequipamento'], ['equipamentos.idequipamento'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['idtecnico'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idos')
    # REMOVIDO: sa.UniqueConstraint('descricao_defeito') para permitir defeitos repetidos
    )
    
    op.create_table('os_itens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idos', sa.Uuid(), nullable=False),
    sa.Column('idproduto', sa.Uuid(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['idos'], ['OS.idos'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idproduto'], ['produtos.idproduto'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    # ADIÇÃO MANUAL: Índice composto único para evitar o mesmo produto duplicado em linhas separadas da mesma OS
    op.create_index(
        'idx_os_produto_unico', # Nome do índice
        'os_itens',             # Tabela alvo
        ['idos', 'idproduto'],  # Colunas combinadas
        unique=True             # Garante a regra de negócio
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOÇÃO MANUAL: Remove o índice composto antes de derrubar a tabela
    op.drop_index('idx_os_produto_unico', table_name='os_itens')
    
    op.drop_table('os_itens')
    op.drop_table('OS')
    # ### end Alembic commands ###
